language: go
sudo: required
go:
- 1.12

matrix:
  include:
    - os: osx
      compiler: clang
      osx_image: xcode10.2
    - os: linux
      compiler: g++

branches:
  only:
    - master

env:
  global:
  - GITHUB_REPO: dfordsoft/yairc
  - GIT_NAME: missdeer
  - GIT_EMAIL: missdeer@dfordsoft.com
deploy:
  - provider: releases
    api_key:
      secure: cLJ7HSA7GuhnMOeHaUe+VjDKcCYKkYxcMNn36BTdGvRsmaJimtepRYrnr85GqpRYZI0chlkNr+ufy6XoAkFgn4P/ms9A1cObFDnzR19Q7V6S2bV7IA0X550aC3Hlyg6wh61saA04cL31rLkBxKUuyZ3XJXYzQIt5pyjVcqb9OQI=
    file:
    - yairc-linux-amd64.tar.gz
    - yairc-windows-amd64.tar.gz
    - yairc-windows-x86.tar.gz
    on:
      condition: $TRAVIS_OS_NAME = linux
      repo: dfordsoft/yairc
      tags: true
    skip_cleanup: true
  - provider: releases
    api_key:
      secure: cLJ7HSA7GuhnMOeHaUe+VjDKcCYKkYxcMNn36BTdGvRsmaJimtepRYrnr85GqpRYZI0chlkNr+ufy6XoAkFgn4P/ms9A1cObFDnzR19Q7V6S2bV7IA0X550aC3Hlyg6wh61saA04cL31rLkBxKUuyZ3XJXYzQIt5pyjVcqb9OQI=
    file:
    - yairc-macos.tar.gz
    on:
      condition: $TRAVIS_OS_NAME = osx
      repo: dfordsoft/yairc
      tags: true
    skip_cleanup: true
before_install:
- if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then sudo apt-get update -qq ; fi
- if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then sudo apt-get install -qq g++-mingw-w64-i686 ; fi
- if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then sudo apt-get install -qq g++-mingw-w64-x86-64 ; fi
install:
- go get github.com/dfordsoft/yairc
script:
- pwd && ls -l
- if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then env CGO_ENABLED=1 GOARCH=amd64 GOOS=linux go build -ldflags="-s -w"  && tar czvf yairc-linux-amd64.tar.gz yairc ; fi
- if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then env CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ LD=x86_64-w64-mingw32-ld GOARCH=amd64 GOOS=windows go build  && tar czvf yairc-windows-amd64.tar.gz yairc.exe ; fi
- if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then env CGO_ENABLED=1 CC=i686-w64-mingw32-gcc CXX=i686-w64-mingw32-g++ LD=i686-w64-mingw32-ld GOARCH=386 GOOS=windows go build  && tar czvf yairc-windows-x86.tar.gz yairc.exe ; fi
- if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then env CGO_ENABLED=1 go build  && tar czvf yairc-macos.tar.gz yairc ; fi
- ls -l
